LESSONS = {
    "A0": [
        {"id": "a0_abc", "title": "Английский алфавит", "topic": "the English alphabet — all 26 letters, pronunciation, and spelling basics"},
        {"id": "a0_numbers", "title": "Цифры от 1 до 20", "topic": "numbers 1-20 in English — counting, pronunciation, and writing"},
        {"id": "a0_greetings", "title": "Приветствия и прощания", "topic": "hello, hi, good morning, goodbye, see you — basic greetings and farewells"},
        {"id": "a0_colors", "title": "Цвета", "topic": "red, blue, green, yellow, black, white — color names with pronunciation"},
        {"id": "a0_days", "title": "Дни недели", "topic": "Monday through Sunday — days of the week and how to use them"},
        {"id": "a0_months", "title": "Месяцы и времена года", "topic": "January to December, spring, summer, autumn, winter"},
        {"id": "a0_family", "title": "Семья", "topic": "mother, father, brother, sister, grandmother, grandfather — family vocabulary"},
        {"id": "a0_body", "title": "Части тела", "topic": "head, hands, legs, eyes, ears, nose, mouth — body parts"},
        {"id": "a0_animals", "title": "Животные", "topic": "cat, dog, bird, fish, horse, cow — common animals"},
        {"id": "a0_food", "title": "Еда и напитки", "topic": "bread, milk, water, apple, meat, rice — basic food vocabulary"},
        {"id": "a0_clothes", "title": "Одежда", "topic": "shirt, pants, dress, shoes, hat, jacket — clothing items"},
        {"id": "a0_weather", "title": "Погода", "topic": "sunny, rainy, cold, hot, windy, cloudy — weather words"},
        {"id": "a0_school", "title": "Школьные предметы", "topic": "book, pen, pencil, desk, teacher, student — classroom vocabulary"},
        {"id": "a0_feelings", "title": "Чувства и эмоции", "topic": "happy, sad, angry, tired, hungry, thirsty — basic emotions"},
        {"id": "a0_house", "title": "Дом и комнаты", "topic": "kitchen, bedroom, bathroom, living room, door, window — house vocabulary"},
    ],
    "A1": [
        {"id": "a1_pronouns", "title": "Личные местоимения", "topic": "I, you, he, she, it, we, they — personal pronouns and when to use them"},
        {"id": "a1_tobe", "title": "Глагол TO BE", "topic": "am, is, are — positive, negative, and question forms of the verb to be"},
        {"id": "a1_present_simple", "title": "Present Simple — настоящее простое", "topic": "Present Simple tense — usage, formation, third person -s, adverbs of frequency"},
        {"id": "a1_articles", "title": "Артикли a/an и the", "topic": "indefinite articles a/an and definite article the — rules and common mistakes"},
        {"id": "a1_questions", "title": "Вопросы с Do и Does", "topic": "forming Yes/No questions and Wh-questions with do/does in Present Simple"},
        {"id": "a1_plurals", "title": "Множественное число существительных", "topic": "regular plurals (-s, -es, -ies) and common irregular plurals (man/men, child/children)"},
        {"id": "a1_have_got", "title": "Have got и Has got", "topic": "have got / has got for possession, appearance, and relationships"},
        {"id": "a1_possessive", "title": "Притяжательные местоимения", "topic": "my, your, his, her, its, our, their — possessive adjectives in context"},
        {"id": "a1_prepositions_place", "title": "Предлоги места", "topic": "in, on, at, under, behind, next to, between, in front of — where things are"},
        {"id": "a1_can", "title": "Модальный глагол Can", "topic": "can/can't for ability, permission, and polite requests"},
        {"id": "a1_there_is", "title": "Конструкция There is / There are", "topic": "there is, there are for describing existence, quantity, and location"},
        {"id": "a1_imperative", "title": "Повелительное наклонение", "topic": "imperative mood — giving commands, instructions, warnings, and invitations"},
        {"id": "a1_this_that", "title": "Указательные местоимения", "topic": "this, that, these, those — pointing to objects near and far"},
        {"id": "a1_present_cont_intro", "title": "Present Continuous — введение", "topic": "Present Continuous basics — am/is/are + verb-ing for actions happening now"},
        {"id": "a1_adjectives_basic", "title": "Прилагательные и порядок слов", "topic": "common adjectives — big/small, old/new, good/bad — and basic word order"},
        {"id": "a1_like_want", "title": "Like, Love, Want + инфинитив", "topic": "like/love/want + to + verb — expressing preferences and desires"},
        {"id": "a1_daily_routine", "title": "Распорядок дня", "topic": "daily routine vocabulary and Present Simple — wake up, have breakfast, go to work"},
        {"id": "a1_time", "title": "Время и часы", "topic": "telling time in English — o'clock, half past, quarter to, quarter past"},
        {"id": "a1_countries", "title": "Страны и национальности", "topic": "country names, nationalities, and languages — Russia/Russian, France/French"},
    ],
    "A2": [
        {"id": "a2_past_simple", "title": "Past Simple — прошедшее простое", "topic": "Past Simple — regular verbs (-ed), irregular verbs, questions with did, negatives with didn't"},
        {"id": "a2_future", "title": "Будущее время: will и going to", "topic": "expressing future with will (predictions, promises) and going to (plans, intentions)"},
        {"id": "a2_present_cont", "title": "Present Continuous — полный обзор", "topic": "Present Continuous for now, around now, future arrangements, and changing situations"},
        {"id": "a2_comparatives", "title": "Степени сравнения прилагательных", "topic": "comparative (-er, more) and superlative (-est, most) — comparing people and things"},
        {"id": "a2_modals", "title": "Модальные глаголы: must, should, might", "topic": "must for obligation, should for advice, might for possibility — basic modals"},
        {"id": "a2_prepositions_time", "title": "Предлоги времени", "topic": "in (months, years), on (days, dates), at (times, holidays) — prepositions of time"},
        {"id": "a2_adverbs", "title": "Наречия частоты", "topic": "always, usually, often, sometimes, rarely, never — frequency adverbs and word order"},
        {"id": "a2_countable", "title": "Исчисляемые и неисчисляемые", "topic": "countable vs uncountable nouns — how much vs how many, a lot of, a few, a little"},
        {"id": "a2_some_any", "title": "Some, Any, No и их производные", "topic": "some/any/no in statements and questions — someone, anything, nowhere"},
        {"id": "a2_wh_questions", "title": "Вопросительные слова", "topic": "what, where, when, why, who, whose, which, how — forming detailed questions"},
        {"id": "a2_past_cont", "title": "Past Continuous — прошедшее длительное", "topic": "was/were doing — actions in progress in the past, when vs while"},
        {"id": "a2_conjunctions", "title": "Союзы: and, but, or, so, because", "topic": "basic conjunctions for connecting ideas in compound sentences"},
        {"id": "a2_quantifiers", "title": "Количественные слова", "topic": "much, many, a lot of, plenty of, a few, a little — expressing quantity precisely"},
        {"id": "a2_polite_requests", "title": "Вежливые просьбы и предложения", "topic": "could you, would you like, shall I, let's — polite requests, offers, and suggestions"},
        {"id": "a2_describing_people", "title": "Описание людей и внешности", "topic": "appearance and personality vocabulary — tall, short, curly hair, friendly, shy"},
        {"id": "a2_offers_suggestions", "title": "Предложения и советы: Shall/Let's/Why don't", "topic": "making suggestions — shall we, let's, why don't we, how about"},
        {"id": "a2_comparisons_asas", "title": "Сравнения: as...as, not as...as", "topic": "comparisons with as + adjective + as — she is as tall as her brother"},
        {"id": "a2_ed_ing_adjectives", "title": "Прилагательные на -ed и -ing", "topic": "bored vs boring, interested vs interesting — difference and usage"},
    ],
    "B1": [
        {"id": "b1_present_perfect", "title": "Present Perfect — настоящее совершённое", "topic": "have/has + past participle — experience, result, duration; ever, never, just, already, yet, since, for"},
        {"id": "b1_first_conditional", "title": "Условные предложения (First Conditional)", "topic": "if + present simple, will + infinitive — real future situations and consequences"},
        {"id": "b1_passive", "title": "Пассивный залог (основы)", "topic": "be + past participle — passive voice in present simple and past simple; by + agent"},
        {"id": "b1_phrasal_verbs", "title": "30 основных фразовых глаголов", "topic": "get up, wake up, look after, give up, turn on/off, put on, take off — top 30 phrasal verbs"},
        {"id": "b1_gerund_inf", "title": "Герундий и инфинитив", "topic": "verb + -ing vs to + verb — rules, exceptions, and verbs that change meaning (stop, remember, try)"},
        {"id": "b1_relative_clauses", "title": "Относительные придаточные", "topic": "who, which, that, where, whose, when — defining and non-defining relative clauses"},
        {"id": "b1_used_to", "title": "Used to / Be used to / Get used to", "topic": "used to for past habits, be used to for familiarity, get used to for adaptation"},
        {"id": "b1_reported_speech", "title": "Косвенная речь (основы)", "topic": "reported speech — tense shift, pronoun changes, reporting verbs (said, told, asked)"},
        {"id": "b1_so_such", "title": "So, Such, Too, Enough", "topic": "so + adjective, such + noun, too + adjective, not enough + noun — intensifiers"},
        {"id": "b1_articles_adv", "title": "Артикли (продвинутый уровень)", "topic": "articles with geographical names, institutions, meals, transport — advanced usage"},
        {"id": "b1_modal_perfect", "title": "Модальные глаголы + перфект", "topic": "must have done, might have done, should have done, can't have done — past speculation"},
        {"id": "b1_question_tags", "title": "Разделительные вопросы", "topic": "you like it, don't you? — question tags; formation rules and intonation"},
        {"id": "b1_past_perfect", "title": "Past Perfect — предпрошедшее время", "topic": "had + past participle — actions before another point in the past"},
        {"id": "b1_make_do", "title": "Make и Do — разница и выражения", "topic": "make a mistake vs do homework — fixed expressions with make and do"},
        {"id": "b1_prepositions_adv", "title": "Предлоги после глаголов и прилагательных", "topic": "depend on, good at, interested in, afraid of — dependent prepositions"},
        {"id": "b1_second_conditional", "title": "Второй тип условных предложений", "topic": "second conditional — if + past simple, would + infinitive for unreal situations"},
        {"id": "b1_ed_ing_adj_adv", "title": "Прилагательные и наречия (продвинуто)", "topic": "adjective vs adverb — quick/quickly, good/well, hard/hardly — advanced usage"},
        {"id": "b1_inf_purpose", "title": "Инфинитив цели: to / in order to / so as to", "topic": "I went to the store to buy milk — expressing purpose with infinitive"},
        {"id": "b1_both_either_neither", "title": "Both, Either, Neither", "topic": "both of us, either of them, neither of us — distributives and agreement"},
    ],
    "B2": [
        {"id": "b2_conditionals_all", "title": "Все типы условных предложений", "topic": "zero, first, second, third, and mixed conditionals — complete comparison and usage"},
        {"id": "b2_reported_adv", "title": "Косвенная речь (продвинутая)", "topic": "advanced reported speech — reporting verbs, embedded questions, modals in reported speech"},
        {"id": "b2_wish", "title": "Wish и If only", "topic": "I wish I had, if only I could, wish + would — expressing wishes and regrets in detail"},
        {"id": "b2_modals_past", "title": "Модальные глаголы в прошлом", "topic": "could have, should have, would have, might have — past possibility, criticism, and regret"},
        {"id": "b2_inversion_intro", "title": "Инверсия (введение)", "topic": "never have I, not only did he, hardly had she — inversion after negative adverbials"},
        {"id": "b2_idioms", "title": "50 важных идиом английского", "topic": "break the ice, hit the nail on the head, piece of cake, spill the beans — common idioms"},
        {"id": "b2_phrasal_adv", "title": "Продвинутые фразовые глаголы", "topic": "come across, get away with, put up with, run out of, look forward to — advanced phrasal verbs"},
        {"id": "b2_linking_words", "title": "Слова-связки для письма и речи", "topic": "however, therefore, furthermore, nevertheless, in addition, on the other hand"},
        {"id": "b2_register", "title": "Формальный и неформальный стиль", "topic": "formal vs informal English — vocabulary, grammar, and when to use each register"},
        {"id": "b2_opinion", "title": "Выражение мнения и аргументация", "topic": "in my opinion, I believe, it seems to me — expressing, agreeing, and disagreeing politely"},
        {"id": "b2_future_forms", "title": "Все формы будущего времени", "topic": "will, going to, present continuous, future continuous, future perfect — all future forms compared"},
        {"id": "b2_causative", "title": "Каузатив: have/get something done", "topic": "I had my hair cut, I got my car fixed — causative structures"},
        {"id": "b2_participle_clauses", "title": "Причастные обороты", "topic": "walking down the street, having finished work — present and past participle clauses"},
        {"id": "b2_unless_in_case", "title": "Unless, In case, Provided that", "topic": "conditional conjunctions — unless it rains, in case you need, provided that you agree"},
        {"id": "b2_emphasis_do", "title": "Эмфаза с DO/DOES/DID", "topic": "I DO like it, she DOES know — using auxiliary for emphasis in speech and writing"},
        {"id": "b2_negative_prefixes", "title": "Отрицательные приставки", "topic": "un-, in-, im-, ir-, dis-, mis- — building negative adjectives and verbs"},
    ],
    "C1": [
        {"id": "c1_inversion_full", "title": "Полная инверсия в английском", "topic": "not only, never, rarely, scarcely, no sooner, little did I, only then — full inversion rules"},
        {"id": "c1_cleft", "title": "Cleft Sentences (расщеплённые предложения)", "topic": "it is/was... that..., what... is/was..., the reason why, the thing that — emphasis structures"},
        {"id": "c1_subjunctive", "title": "Сослагательное наклонение", "topic": "I suggest that he go, it is essential that she be informed — subjunctive mood in formal English"},
        {"id": "c1_discourse", "title": "Дискурсивные маркеры", "topic": "discourse markers — structuring academic speech and writing; stance, hedging, boosting"},
        {"id": "c1_academic_vocab", "title": "Академическая лексика (AWL)", "topic": "academic word list — key vocabulary for university, research, and professional contexts"},
        {"id": "c1_modal_nuance", "title": "Нюансы модальных глаголов", "topic": "subtle differences — may vs might, must vs have to, shall vs will, needn't vs don't need to"},
        {"id": "c1_ellipsis", "title": "Эллипсис и субституция", "topic": "ellipsis — leaving words out; substitution with one/ones, do so, this/that — natural economy of language"},
        {"id": "c1_colocations", "title": "Устойчивые словосочетания (collocations)", "topic": "make a decision, take a risk, heavy rain, strong coffee, highly recommended — advanced collocations"},
        {"id": "c1_narrative_tenses", "title": "Нарративные времена", "topic": "past simple, past continuous, past perfect, past perfect continuous — telling stories naturally"},
        {"id": "c1_hedging", "title": "Хеджирование и смягчение", "topic": "it could be argued, to some extent, it appears that — academic hedging and softening claims"},
        {"id": "c1_idioms_adv", "title": "Продвинутые идиомы C1", "topic": "burn the midnight oil, go the extra mile, read between the lines — sophisticated idioms"},
        {"id": "c1_conditionals_mixed", "title": "Смешанные условные (Mixed Conditionals)", "topic": "mixed conditionals — if I had studied, I would be successful now — combining tenses"},
        {"id": "c1_future_in_past", "title": "Future in the Past", "topic": "was going to, was about to, was to — expressing future from past perspective"},
        {"id": "c1_passive_advanced", "title": "Пассивный залог (продвинутый)", "topic": "passive with reporting verbs, have/get something done, passive with modals, passive infinitive"},
    ],
    "C2": [
        {"id": "c2_nuance", "title": "Лексические нюансы и синонимы", "topic": "subtle differences — big/large/great/enormous, say/tell/speak/utter, look/gaze/glance/stare"},
        {"id": "c2_register_full", "title": "Полный контроль регистров речи", "topic": "full register control — adapting language from street slang to parliamentary debate"},
        {"id": "c2_idioms_master", "title": "Мастерство идиом и метафор", "topic": "sophisticated idioms and metaphorical language for near-native fluency and literary expression"},
        {"id": "c2_rhetoric", "title": "Риторические приёмы", "topic": "parallelism, antithesis, rhetorical questions, anaphora, chiasmus — advanced rhetorical devices"},
        {"id": "c2_culture", "title": "Культурные отсылки и аллюзии", "topic": "cultural references in English — Shakespeare, the Bible, mythology, historical events, pop culture"},
        {"id": "c2_irony", "title": "Ирония, сарказм и understatement", "topic": "understanding and using irony, sarcasm, and British understatement in natural conversation"},
        {"id": "c2_cohesion", "title": "Когезия и когерентность текста", "topic": "making writing flow — lexical chains, reference, substitution, parallelism at paragraph level"},
        {"id": "c2_pragmatics", "title": "Прагматика и импликатура", "topic": "reading between the lines — implied meaning, conversational implicature, face and politeness theory"},
        {"id": "c2_fronting", "title": "Fronting и тематизация", "topic": "moving elements to the front of sentences for emphasis — that I don't know, him I trust"},
        {"id": "c2_binomials", "title": "Биномы и триномы", "topic": "fixed pairs and triples — rock and roll, safe and sound, ready and willing, lock stock and barrel"},
        {"id": "c2_euphemisms", "title": "Эвфемизмы и политкорректность", "topic": "between jobs, passed away, vertically challenged — political correctness and softening language"},
    ],
}

LEVEL_NAMES = {
    "A0": "Начальный нулевой", "A1": "Начинающий", "A2": "Элементарный",
    "B1": "Средний", "B2": "Выше среднего", "C1": "Продвинутый", "C2": "Профессиональный",
}

LEVEL_ORDER = ["A0", "A1", "A2", "B1", "B2", "C1", "C2"]


def get_lessons_for_level(level):
    return LESSONS.get(level, [])

def get_all_lessons():
    return LESSONS

def get_next_level(current_level):
    try:
        idx = LEVEL_ORDER.index(current_level)
        return LEVEL_ORDER[min(idx + 1, len(LEVEL_ORDER) - 1)]
    except ValueError:
        return "A1"
